/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/projects/{projectId}/agent/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAgentRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/agent/requests/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAgentRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            code: string;
            message: string;
            traceId: string;
            details: Record<string, never>;
        };
        CreateAgentRequest: {
            /** @enum {string} */
            purpose: "FINDING_EXPLANATION" | "PR_SUMMARY";
            scanJobId: string;
            reportSha256: string;
            /** @description Required for PR_SUMMARY and must match an applied PR head revision with a completed report for scanJobId and reportSha256; null for a standalone Finding explanation. */
            prHeadRevisionId: string | null;
            findingIds: string[];
            documentVersionIds: string[];
        };
        AgentRequest: {
            id: string;
            projectId: string;
            requesterId: string;
            traceId: string;
            /** @enum {string} */
            purpose: "FINDING_EXPLANATION" | "PR_SUMMARY";
            /** @enum {string} */
            state: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED";
            bindings: components["schemas"]["VersionBindings"];
            result: components["schemas"]["AgentResult"] | null;
            failure: components["schemas"]["AgentFailure"] | null;
            usage: components["schemas"]["AgentUsage"] | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        VersionBindings: {
            scanJobId: string;
            reportSha256: string;
            prHeadRevisionId: string | null;
            findingIds: string[];
            documentVersions: components["schemas"]["DocumentVersionBinding"][];
            promptVersion: string;
            modelProfileVersion: string;
            modelProtocolVersion: string;
            modelId: string;
            /** @enum {string} */
            outputSchemaVersion: "0.1.0";
            priceCatalogVersion: string;
            inputDigest: string;
        };
        DocumentVersionBinding: {
            documentVersionId: string;
            contentSha256: string;
        };
        AgentResult: {
            conclusion: string;
            ruleBasis: string[];
            claims: string[];
            suggestions: components["schemas"]["Suggestion"][];
            citations: components["schemas"]["VerifiedCitation"][];
            /** @enum {string} */
            evidenceCoverage: "NONE" | "PARTIAL" | "COMPLETE";
        };
        Suggestion: {
            text: string;
            /** @enum {string} */
            kind: "HUMAN_VERIFICATION" | "LOW_RISK_DIRECTION";
            /** @constant */
            requiresHumanReview: true;
        };
        VerifiedCitation: {
            citationId: string;
            /** @enum {string} */
            source: "SCANNER_EVIDENCE" | "PROJECT_DOCUMENT";
            label: string;
            projectId: string;
            scanJobId: string | null;
            reportSha256: string | null;
            evidenceId: string | null;
            documentVersionId: string | null;
            contentSha256: string | null;
            fragmentIndex: number | null;
            fragmentSha256: string | null;
        };
        AgentFailure: {
            /** @enum {string} */
            code: "MODEL_DISABLED" | "MODEL_UNAVAILABLE" | "MODEL_TIMEOUT" | "QUOTA_EXHAUSTED" | "OUTPUT_INVALID" | "CITATION_INVALID" | "AUTHORIZATION_REVOKED" | "INTERNAL_ERROR";
            message: string;
        };
        AgentUsage: {
            inputTokens: number;
            outputTokens: number;
            latencyMs: number;
            providerLatencyMs: number | null;
            estimatedCostMicrousd: number;
            actualCostMicrousd: number | null;
            providerResponseId: string | null;
            actualModelId: string | null;
        };
    };
    responses: {
        /** @description Uniform API error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        ProjectId: string;
        RequestId: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createAgentRequest: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAgentRequest"];
            };
        };
        responses: {
            /** @description New or identical replay; may already be FAILED when disabled or quota exhausted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRequest"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getAgentRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project-authorized request snapshot; terminal result is immutable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRequest"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
}
