/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/projects/{projectId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjectDocuments"];
        put?: never;
        /** @description Maintainer only. A new Idempotency-Key creates a new immutable version of documentKey. */
        post: operations["uploadProjectDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/documents/{documentId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjectDocumentVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/documents/{documentId}/versions/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProjectDocumentVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/documents/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Read-only retrieval over 1-10 explicit same-Project versions; all must be authorized or the request fails. No model or external search. */
        post: operations["searchProjectDocumentVersions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            code: string;
            message: string;
            traceId: string;
            details: Record<string, never>;
        };
        DocumentVersion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            documentId: string;
            /** Format: uuid */
            projectId: string;
            documentKey: string;
            versionNumber: number;
            mediaType: string;
            content: string;
            contentSha256: string;
            byteSize: number;
            fragmentCount: number;
            /** Format: uuid */
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
        };
        DocumentPage: {
            items: components["schemas"]["DocumentSummary"][];
            page: number;
            size: number;
            total: number;
        };
        DocumentSummary: {
            /** Format: uuid */
            id: string;
            documentKey: string;
            latestVersionNumber: number;
            /** Format: uuid */
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
        };
        DocumentVersionPage: {
            items: components["schemas"]["DocumentVersionSummary"][];
            page: number;
            size: number;
            total: number;
        };
        DocumentVersionSummary: {
            /** Format: uuid */
            id: string;
            versionNumber: number;
            mediaType: string;
            contentSha256: string;
            byteSize: number;
            fragmentCount: number;
            /** Format: uuid */
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
        };
        SearchRequest: {
            versionIds: string[];
            query: string;
        };
        SearchResponse: {
            items: components["schemas"]["Fragment"][];
        };
        Fragment: {
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            documentVersionId: string;
            contentSha256: string;
            fragmentIndex: number;
            startOffset: number;
            fragmentSha256: string;
            content: string;
        };
    };
    responses: {
        /** @description Uniform traceable API error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        ProjectId: string;
        DocumentId: string;
        VersionId: string;
        IdempotencyKey: string;
        Page: number;
        Size: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProjectDocuments: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project-visible document metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPage"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    uploadProjectDocument: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    documentKey: string;
                    /**
                     * Format: binary
                     * @description Strict UTF-8, <=262144 bytes, text/markdown (.md/.markdown) or text/plain (.txt).
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Identical idempotent replay */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentVersion"];
                };
            };
            /** @description New immutable version */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentVersion"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            413: components["responses"]["Error"];
        };
    };
    listProjectDocumentVersions: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                documentId: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable version metadata, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentVersionPage"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getProjectDocumentVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                documentId: components["parameters"]["DocumentId"];
                versionId: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exact immutable version, including full text for authorized Project viewers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentVersion"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    searchProjectDocumentVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description At most four source-labeled fragments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
}
