/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/agent/credentials/deepseek": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Metadata only. Authenticated configured owner required; missing master or corrupt ciphertext fails closed. Origin, when present, must match the configured loopback UI origin. */
        get: operations["getDeepSeekCredentialStatus"];
        /** @description Write/replace with a new version; no automatic retry. Origin must exactly match configured UI origin. <=512 raw JSON bytes, no duplicate/trailing/unknown fields. No validity/balance check; never log or persist browser input. */
        put: operations["writeDeepSeekCredential"];
        post?: never;
        /** @description Remove local encrypted slot; absent is idempotent. Does not revoke provider Key or erase snapshots/in-flight requests. No fallback to other credentials. Corrupt slot/wrong master preserved with 503. Existing results/audit retained. */
        delete: operations["deleteDeepSeekCredential"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WriteCredentialRequest: {
            apiKey: string;
        };
        CredentialStatus: {
            configured: boolean;
            /** Format: uuid */
            credentialVersion: string | null;
            /** Format: date-time */
            updatedAt: string | null;
        };
        ApiError: {
            code: string;
            message: string;
            traceId: string;
            details: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Metadata only; no Key/suffix/fingerprint. An audit failure after mutation may require manual status refresh; never auto-retry writes. */
        Status: {
            headers: {
                "Cache-Control"?: "no-store";
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CredentialStatus"];
            };
        };
        /** @description Stable error/traceId, never input/rejectedValue/provider response/paths. */
        Error: {
            headers: {
                "Cache-Control"?: "no-store";
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        /** @description Browser supplies this header. No cross-origin API access; public origins not permitted. */
        Origin: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getDeepSeekCredentialStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Status"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    writeDeepSeekCredential: {
        parameters: {
            query?: never;
            header: {
                /** @description Browser supplies this header. No cross-origin API access; public origins not permitted. */
                Origin: components["parameters"]["Origin"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriteCredentialRequest"];
            };
        };
        responses: {
            200: components["responses"]["Status"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            415: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    deleteDeepSeekCredential: {
        parameters: {
            query?: never;
            header: {
                /** @description Browser supplies this header. No cross-origin API access; public origins not permitted. */
                Origin: components["parameters"]["Origin"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Status"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
}
