/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/projects/{projectId}/repositories/{repositoryId}/baselines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBaselineVersions"];
        put?: never;
        /** Promote a successful scan to an immutable baseline version, or reselect its existing version */
        post: operations["promoteBaseline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/repositories/{repositoryId}/baselines/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getActiveBaseline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/repositories/{repositoryId}/baselines/{baselineVersionId}/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append an audited selection without modifying any baseline version */
        post: operations["selectBaselineVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/repositories/{repositoryId}/comparisons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Persist deterministic NEW, EXISTING and RESOLVED Finding sets */
        post: operations["compareWithActiveBaseline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ScopeRequest: {
            targetBranch: string;
            /** Format: uuid */
            ruleSetVersionId: string;
        };
        PromoteRequest: components["schemas"]["ScopeRequest"] & {
            /** Format: uuid */
            scanJobId: string;
            commitSha: string;
        };
        CompareRequest: components["schemas"]["ScopeRequest"] & {
            /** Format: uuid */
            candidateJobId: string;
        };
        BaselineVersion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            repositoryId: string;
            targetBranch: string;
            /** Format: uuid */
            ruleSetVersionId: string;
            version: number;
            /** Format: uuid */
            scanJobId: string;
            commitSha: string;
            reportSha256: string;
            /** @constant */
            fingerprintVersion: "platform-finding-v1";
            /** Format: uuid */
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            active: boolean;
            selectionVersion: number;
        };
        ClassifiedFinding: {
            /** @enum {string} */
            classification: "NEW" | "EXISTING" | "RESOLVED";
            fingerprint: string;
            payloadSha256: string;
            ruleId: string;
            ruleVersion: string;
            severity: string;
            scannerFindingId: string;
        };
        Comparison: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            baselineVersionId: string;
            /** Format: uuid */
            candidateJobId: string;
            candidateReportSha256: string;
            /** @constant */
            fingerprintVersion: "platform-finding-v1";
            /** Format: date-time */
            createdAt: string;
            findings: components["schemas"]["ClassifiedFinding"][];
            newCount: number;
            existingCount: number;
            resolvedCount: number;
        };
    };
    responses: {
        /** @description Invalid request metadata */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Resource absent or not visible in this Project */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Scan or baseline state is incompatible */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Report cannot yield a supported stable Finding identity */
        InvalidReport: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: {
        ProjectId: string;
        RepositoryId: string;
        BaselineVersionId: string;
        TargetBranch: string;
        RuleSetVersionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listBaselineVersions: {
        parameters: {
            query: {
                targetBranch: components["parameters"]["TargetBranch"];
                ruleSetVersionId: components["parameters"]["RuleSetVersionId"];
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                repositoryId: components["parameters"]["RepositoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versions, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaselineVersion"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    promoteBaseline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                repositoryId: components["parameters"]["RepositoryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromoteRequest"];
            };
        };
        responses: {
            /** @description Baseline version selected */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaselineVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["InvalidReport"];
        };
    };
    getActiveBaseline: {
        parameters: {
            query: {
                targetBranch: components["parameters"]["TargetBranch"];
                ruleSetVersionId: components["parameters"]["RuleSetVersionId"];
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                repositoryId: components["parameters"]["RepositoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Currently selected immutable version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaselineVersion"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    selectBaselineVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                repositoryId: components["parameters"]["RepositoryId"];
                baselineVersionId: components["parameters"]["BaselineVersionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScopeRequest"];
            };
        };
        responses: {
            /** @description Selected version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaselineVersion"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    compareWithActiveBaseline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                repositoryId: components["parameters"]["RepositoryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Immutable comparison; identical inputs return the same ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comparison"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["InvalidReport"];
        };
    };
}
