/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/projects/{projectId}/repositories/{repositoryId}/gate-evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Persist an immutable PASS/FAIL/ERROR decision for a successful scan or a failed scan error */
        post: operations["evaluateGovernanceGate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/repositories/{repositoryId}/gate-evaluations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGovernanceGate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/repositories/{repositoryId}/policy-exceptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPolicyExceptions"];
        put?: never;
        post: operations["createPolicyException"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/repositories/{repositoryId}/policy-exceptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPolicyException"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/repositories/{repositoryId}/policy-exceptions/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revokePolicyException"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        EvaluateRequest: {
            targetBranch: string;
            /** Format: uuid */
            ruleSetVersionId: string;
            /** Format: uuid */
            candidateJobId: string;
        };
        GateEvaluation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            repositoryId: string;
            targetBranch: string;
            /** Format: uuid */
            ruleSetVersionId: string;
            /** Format: uuid */
            candidateJobId: string;
            /** Format: uuid */
            comparisonId?: string | null;
            /** Format: uuid */
            baselineVersionId?: string | null;
            /** @enum {string} */
            outcome: "PASS" | "FAIL" | "ERROR";
            /** @enum {integer} */
            ciExitCode: 0 | 2 | 64 | 70;
            /** @enum {string|null} */
            errorKind?: "CONFIGURATION" | "EXECUTION_OR_CONTRACT" | null;
            errorCode?: string | null;
            /** @constant */
            policyVersion: "default-new-high-critical-v1";
            /** @constant */
            fingerprintVersion: "platform-finding-v1";
            newCount: number;
            existingCount: number;
            resolvedCount: number;
            blockedCount: number;
            matchedExceptionVersionIds: string[];
            /** Format: date-time */
            evaluatedAt: string;
        };
        CreateExceptionRequest: {
            targetBranch: string;
            /** Format: uuid */
            ruleSetVersionId: string;
            /** @enum {string} */
            scopeType: "FINGERPRINT" | "RULE";
            scopeValue: string;
            reason: string;
            /** Format: date-time */
            effectiveAt: string;
            /** Format: date-time */
            expiresAt: string;
        };
        RevokeRequest: {
            reason: string;
        };
        PolicyException: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            repositoryId: string;
            targetBranch: string;
            /** Format: uuid */
            ruleSetVersionId: string;
            /** @enum {string} */
            scopeType: "FINGERPRINT" | "RULE";
            scopeValue: string;
            reason: string;
            /** Format: date-time */
            effectiveAt: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: uuid */
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            revokedBy?: string | null;
            /** Format: date-time */
            revokedAt?: string | null;
            revocationReason?: string | null;
            /** Format: uuid */
            currentVersionId: string;
            version: number;
            /** @enum {string} */
            status: "PENDING" | "ACTIVE" | "EXPIRED" | "REVOKED";
        };
    };
    responses: {
        /** @description Invalid input or key */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Absent or outside the authenticated Project */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Key reused with different input or incompatible resource state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: {
        ProjectId: string;
        RepositoryId: string;
        Id: string;
        IdempotencyKey: string;
        TargetBranch: string;
        RuleSetVersionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    evaluateGovernanceGate: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                projectId: components["parameters"]["ProjectId"];
                repositoryId: components["parameters"]["RepositoryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluateRequest"];
            };
        };
        responses: {
            /** @description Persisted result; repeated identical key returns the same result */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateEvaluation"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getGovernanceGate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                repositoryId: components["parameters"]["RepositoryId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable gate result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateEvaluation"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listPolicyExceptions: {
        parameters: {
            query: {
                targetBranch: components["parameters"]["TargetBranch"];
                ruleSetVersionId: components["parameters"]["RuleSetVersionId"];
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                repositoryId: components["parameters"]["RepositoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exceptions in one comparison scope */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyException"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createPolicyException: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                repositoryId: components["parameters"]["RepositoryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExceptionRequest"];
            };
        };
        responses: {
            /** @description Created exception */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyException"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getPolicyException: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                repositoryId: components["parameters"]["RepositoryId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exception and derived current status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyException"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    revokePolicyException: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                repositoryId: components["parameters"]["RepositoryId"];
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeRequest"];
            };
        };
        responses: {
            /** @description Revoked exception */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyException"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
}
