/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/projects/{projectId}/repositories/{repositoryId}/github/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGithubRepositoryLink"];
        /** Maintainer binds an immutable numeric GitHub repository identity */
        put: operations["linkGithubRepository"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/repositories/{repositoryId}/github/pull-requests/{externalId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the signed-webhook-derived current PR head and attached gate */
        get: operations["getGithubPullRequestHead"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/github/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify HMAC-SHA256 and apply a monotonic GitHub PR event */
        post: operations["receiveGithubWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        NumericId: string;
        CommitSha: string;
        LinkRequest: {
            providerRepositoryId: components["schemas"]["NumericId"];
            ownerName: string;
            repositoryName: string;
        };
        RepositoryLink: {
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            repositoryId: string;
            /** @constant */
            provider: "github";
            providerRepositoryId: components["schemas"]["NumericId"];
            ownerName: string;
            repositoryName: string;
            /** Format: uuid */
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
        };
        PullRequestHead: {
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            repositoryId: string;
            externalId: components["schemas"]["NumericId"];
            headSha: components["schemas"]["CommitSha"];
            baseSha: components["schemas"]["CommitSha"];
            targetBranch: string;
            /** Format: date-time */
            eventAt: string;
            /** Format: uuid */
            currentGateEvaluationId?: string;
        };
        WebhookResult: {
            /** Format: uuid */
            deliveryId: string;
            /** @enum {string} */
            disposition: "RECEIVED" | "APPLIED" | "STALE" | "IGNORED" | "UNLINKED";
            replay: boolean;
        };
    };
    responses: never;
    parameters: {
        ProjectId: string;
        RepositoryId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getGithubRepositoryLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                repositoryId: components["parameters"]["RepositoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repository link */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryLink"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Link is absent or not visible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    linkGithubRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                repositoryId: components["parameters"]["RepositoryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkRequest"];
            };
        };
        responses: {
            /** @description Repository linked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryLink"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Maintainer required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Project or repository is not visible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Repository identity already bound elsewhere */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getGithubPullRequestHead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                repositoryId: components["parameters"]["RepositoryId"];
                externalId: components["schemas"]["NumericId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current PR head */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PullRequestHead"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description PR is absent or not visible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    receiveGithubWebhook: {
        parameters: {
            query?: never;
            header: {
                "X-GitHub-Delivery": string;
                "X-GitHub-Event": string;
                "X-Hub-Signature-256": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Authenticated delivery recorded or replayed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookResult"];
                };
            };
            /** @description Invalid signature or delivery */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Delivery ID reused for different bytes */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Webhook secret is not configured; fails closed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
