/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/projects/{projectId}/repositories/{repositoryId}/gate-evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listGovernanceGates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/repositories/{repositoryId}/comparisons/{comparisonId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGovernanceComparison"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/repositories/{repositoryId}/github/pull-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listGithubPullRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GatePage: {
            items: components["schemas"]["GateEvaluation"][];
            page: number;
            size: number;
            hasMore: boolean;
        };
        PullRequestPage: {
            items: components["schemas"]["PullRequest"][];
            page: number;
            size: number;
            hasMore: boolean;
        };
        GateEvaluation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            repositoryId: string;
            targetBranch: string;
            /** Format: uuid */
            ruleSetVersionId: string;
            /** Format: uuid */
            candidateJobId?: string | null;
            /** Format: uuid */
            comparisonId?: string | null;
            /** Format: uuid */
            baselineVersionId?: string | null;
            /** @enum {string} */
            outcome: "PASS" | "FAIL" | "ERROR";
            /** @enum {integer} */
            ciExitCode: 0 | 2 | 64 | 70;
            errorKind?: string | null;
            errorCode?: string | null;
            policyVersion: string;
            fingerprintVersion: string;
            newCount: number;
            existingCount: number;
            resolvedCount: number;
            blockedCount: number;
            matchedExceptionVersionIds: string[];
            /** Format: date-time */
            evaluatedAt: string;
        };
        Comparison: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            baselineVersionId: string;
            /** Format: uuid */
            candidateJobId: string;
            candidateReportSha256: string;
            fingerprintVersion: string;
            /** Format: date-time */
            createdAt: string;
            findings: components["schemas"]["ClassifiedFinding"][];
            newCount: number;
            existingCount: number;
            resolvedCount: number;
        };
        ClassifiedFinding: {
            /** @enum {string} */
            classification: "NEW" | "EXISTING" | "RESOLVED";
            fingerprint: string;
            payloadSha256: string;
            ruleId: string;
            ruleVersion: string;
            severity: string;
            scannerFindingId: string;
        };
        PullRequest: {
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            repositoryId: string;
            externalId: string;
            headSha: string;
            baseSha: string;
            targetBranch: string;
            /** Format: date-time */
            eventAt: string;
            /** Format: uuid */
            currentGateEvaluationId?: string | null;
        };
    };
    responses: {
        /** @description Invalid scope or pagination */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Missing or outside the authorized Project */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: {
        ProjectId: string;
        RepositoryId: string;
        TargetBranch: string;
        RuleSetVersionId: string;
        Page: number;
        Size: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listGovernanceGates: {
        parameters: {
            query: {
                targetBranch: components["parameters"]["TargetBranch"];
                ruleSetVersionId: components["parameters"]["RuleSetVersionId"];
                pullRequestId?: string;
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                repositoryId: components["parameters"]["RepositoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest evaluations first, filtered by exact scope and optional PR */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatePage"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getGovernanceComparison: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                repositoryId: components["parameters"]["RepositoryId"];
                comparisonId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable NEW, EXISTING and RESOLVED finding snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comparison"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listGithubPullRequests: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                repositoryId: components["parameters"]["RepositoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Observed PR heads, newest updated first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PullRequestPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
}
