/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects visible to the caller */
        get: operations["listProjects"];
        put?: never;
        /** Create a project and make the caller its maintainer */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** Get a project visible to the caller */
        get: operations["getProject"];
        put?: never;
        post?: never;
        /** Delete a project and its memberships as a maintainer */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        /** Update a project name as a maintainer */
        patch: operations["updateProject"];
        trace?: never;
    };
    "/api/v1/projects/{projectId}/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["listRepositories"];
        put?: never;
        post: operations["createRepository"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/repositories/{repositoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                repositoryId: components["parameters"]["RepositoryId"];
            };
            cookie?: never;
        };
        get: operations["getRepository"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/repositories/{repositoryId}/rule-sets": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                repositoryId: components["parameters"]["RepositoryId"];
            };
            cookie?: never;
        };
        get: operations["listRuleSets"];
        put?: never;
        post: operations["createRuleSet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/repositories/{repositoryId}/rule-sets/{ruleSetId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                repositoryId: components["parameters"]["RepositoryId"];
                ruleSetId: string;
            };
            cookie?: never;
        };
        get: operations["listRuleSetVersions"];
        put?: never;
        post: operations["createRuleSetVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/scan-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get: operations["listScanJobs"];
        put?: never;
        post: operations["submitScanJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/scan-jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get: operations["getScanJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/scan-jobs/{jobId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelScanJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/scan-jobs/{jobId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get: operations["getScanResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/scan-jobs/{jobId}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get: operations["listFindings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/scan-jobs/{jobId}/evidences/{evidenceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                jobId: components["parameters"]["JobId"];
                evidenceId: string;
            };
            cookie?: never;
        };
        get: operations["getEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/scan-jobs/{jobId}/findings/{findingId}/disposition": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                jobId: components["parameters"]["JobId"];
                findingId: components["parameters"]["FindingId"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["setFindingDisposition"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/scan-jobs/{jobId}/findings/{findingId}/dispositions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                jobId: components["parameters"]["JobId"];
                findingId: components["parameters"]["FindingId"];
            };
            cookie?: never;
        };
        get: operations["listFindingDispositions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** List members of a project visible to the caller */
        get: operations["listProjectMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/members/{actorId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                actorId: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Add a member or replace its role as a maintainer */
        put: operations["setProjectMember"];
        post?: never;
        /** Remove a member as a maintainer */
        delete: operations["removeProjectMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateProjectRequest: {
            key: string;
            name: string;
        };
        UpdateProjectRequest: {
            name: string;
            /** Format: int64 */
            version: number;
        };
        SetProjectMemberRequest: {
            role: components["schemas"]["ProjectMemberRole"];
        };
        Project: {
            /** Format: uuid */
            id: string;
            key: string;
            name: string;
            /** Format: uuid */
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: int64 */
            version: number;
        };
        ProjectPage: {
            items: components["schemas"]["Project"][];
            page: number;
            size: number;
            /** Format: int64 */
            total: number;
        };
        ProjectMember: {
            /** Format: uuid */
            actorId: string;
            role: components["schemas"]["ProjectMemberRole"];
            /** Format: date-time */
            createdAt: string;
        };
        /** @enum {string} */
        ProjectMemberRole: "MAINTAINER" | "VIEWER";
        ProjectMemberPage: {
            items: components["schemas"]["ProjectMember"][];
            page: number;
            size: number;
            /** Format: int64 */
            total: number;
        };
        CreateRepositoryRequest: {
            key: string;
            name: string;
            mountPath: string;
        };
        Repository: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            key: string;
            name: string;
            mountPath: string;
            scannerIdentity: string;
            /** Format: uuid */
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: int64 */
            version: number;
        };
        CreateRuleSetRequest: {
            key: string;
            name: string;
        };
        CreateRuleSetVersionRequest: {
            yaml: string;
        };
        RuleSet: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            repositoryId: string;
            key: string;
            name: string;
            /** Format: uuid */
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
        };
        RuleSetVersion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ruleSetId: string;
            version: number;
            yaml: string;
            sha256: components["schemas"]["Sha256"];
            scannerVersion: string;
            /** @constant */
            schemaVersion: "0.1.0";
            /** Format: uuid */
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
        };
        SubmitScanJobRequest: {
            /** Format: uuid */
            repositoryId: string;
            /** Format: uuid */
            ruleSetVersionId: string;
        };
        ScanJob: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            repositoryId: string;
            /** Format: uuid */
            ruleSetVersionId: string;
            /** @enum {string} */
            status: "QUEUED" | "RUNNING" | "CANCEL_REQUESTED" | "SUCCEEDED" | "FAILED" | "CANCELLED";
            /** @enum {string|null} */
            outcome?: "PASS" | "VIOLATION" | null;
            /** Format: uuid */
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            completedAt?: string | null;
            attempt: number;
            /** Format: int64 */
            version: number;
            failureCode?: string | null;
            failureMessage?: string | null;
            reportSha256?: components["schemas"]["Sha256"] | null;
        };
        SourceLocation: {
            path: string;
            startLine: number;
            startColumn: number;
            endLine: number;
            endColumn: number;
        };
        Finding: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            jobId: string;
            scannerFindingId: string;
            fingerprint: components["schemas"]["Sha256"];
            ruleId: string;
            ruleVersion: string;
            /** @enum {string} */
            severity: "low" | "medium" | "high" | "critical";
            subjectId: string;
            message: string;
            location?: components["schemas"]["SourceLocation"] | null;
            disposition: components["schemas"]["FindingDisposition"];
            /** Format: int64 */
            version: number;
            evidenceIds: string[];
        };
        Evidence: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            jobId: string;
            scannerEvidenceId: string;
            kind: string;
            summary: string;
            location: components["schemas"]["SourceLocation"];
        };
        /** @enum {string} */
        FindingDisposition: "OPEN" | "FALSE_POSITIVE" | "RISK_ACCEPTED";
        SetDispositionRequest: {
            disposition: components["schemas"]["FindingDisposition"];
            reason: string;
            /** Format: int64 */
            version: number;
        };
        Disposition: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            findingId: string;
            previousDisposition: components["schemas"]["FindingDisposition"];
            newDisposition: components["schemas"]["FindingDisposition"];
            reason: string;
            /** Format: uuid */
            actorId: string;
            /** Format: date-time */
            occurredAt: string;
            /** Format: int64 */
            version: number;
        };
        Sha256: string;
        ApiError: {
            code: string;
            message: string;
            traceId: string;
            details: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Invalid or malformed request */
        BadRequest: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description OIDC bearer token is missing or invalid */
        Unauthorized: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Caller is a member but lacks the required role or permission */
        Forbidden: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Project does not exist or is not visible to the caller */
        ProjectNotFound: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Unique key, optimistic version, or last-maintainer invariant conflict */
        Conflict: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        ProjectId: string;
        Page: number;
        Size: number;
        RepositoryId: string;
        JobId: string;
        FindingId: string;
    };
    requestBodies: never;
    headers: {
        /** @description Lowercase 32-character hexadecimal request correlation identifier */
        RequestId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProjects: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of projects for which the caller is a member */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Project created */
            201: {
                headers: {
                    Location?: string;
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project found and caller is a member */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["ProjectNotFound"];
        };
    };
    deleteProject: {
        parameters: {
            query: {
                /** @description Expected project version for optimistic concurrency */
                version: number;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project and memberships deleted; audit records are retained */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["ProjectNotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description Project updated and its version incremented */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["ProjectNotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listRepositories: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered repositories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repository"][];
                };
            };
            404: components["responses"]["ProjectNotFound"];
        };
    };
    createRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRepositoryRequest"];
            };
        };
        responses: {
            /** @description Repository registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repository"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["ProjectNotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                repositoryId: components["parameters"]["RepositoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repository details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repository"];
                };
            };
            404: components["responses"]["ProjectNotFound"];
        };
    };
    listRuleSets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                repositoryId: components["parameters"]["RepositoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rule sets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleSet"][];
                };
            };
        };
    };
    createRuleSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                repositoryId: components["parameters"]["RepositoryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRuleSetRequest"];
            };
        };
        responses: {
            /** @description Rule set created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleSet"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    listRuleSetVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                repositoryId: components["parameters"]["RepositoryId"];
                ruleSetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable rule set versions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleSetVersion"][];
                };
            };
        };
    };
    createRuleSetVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                repositoryId: components["parameters"]["RepositoryId"];
                ruleSetId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRuleSetVersionRequest"];
            };
        };
        responses: {
            /** @description Validated rule set version */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleSetVersion"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listScanJobs: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scan job history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanJob"][];
                };
            };
        };
    };
    submitScanJob: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitScanJobRequest"];
            };
        };
        responses: {
            /** @description Scan job queued or existing identical job returned */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanJob"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    getScanJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scan job state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanJob"];
                };
            };
            404: components["responses"]["ProjectNotFound"];
        };
    };
    cancelScanJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation requested or queued job cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanJob"];
                };
            };
        };
    };
    getScanResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Original validated canonical Scanner report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    listFindings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Normalized findings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"][];
                };
            };
        };
    };
    getEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                jobId: components["parameters"]["JobId"];
                evidenceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evidence without source content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evidence"];
                };
            };
        };
    };
    setFindingDisposition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                jobId: components["parameters"]["JobId"];
                findingId: components["parameters"]["FindingId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetDispositionRequest"];
            };
        };
        responses: {
            /** @description Finding disposition updated and audited */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    listFindingDispositions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                jobId: components["parameters"]["JobId"];
                findingId: components["parameters"]["FindingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Append-only disposition history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Disposition"][];
                };
            };
        };
    };
    listProjectMembers: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of project members */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMemberPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["ProjectNotFound"];
        };
    };
    setProjectMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                actorId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetProjectMemberRequest"];
            };
        };
        responses: {
            /** @description Membership was created or updated */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMember"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["ProjectNotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    removeProjectMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                actorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Membership removed */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Project is hidden from the caller or the member does not exist */
            404: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
}
